### ISSUE TITLE
Error scraping from TPDB

### ISSUE THREAD

**Issue by floydcg** [stashapp/stash#3971]
Running the latest nightly g170f45c4.
When scraping TPDB stashdb instance, it will throw this error about 3 seconds after hitting scrape.

`scrapeMultiScenes: input: scrapeMultiScenes {"networkErrors":null,"graphqlErrors":[{"message":"Internal server error","path":["findScenesBySceneFingerprints",16,0,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",16,1,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,0,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,1,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,2,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,3,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,4,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,5,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,6,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,7,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,8,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}},{"message":"Internal server error","path":["findScenesBySceneFingerprints",33,9,"studio","parent","name"],"locations":[{"line":70,"column":3}],"extensions":{"category":"internal"}}]}'

returning to an older nightly build restores scraping.

**Comment by Maista6969** [comment]
The devs over at TPDB have [pushed a fix](https://discord.com/channels/660959182085685258/1028364051656495155/1135610699977072801) for this, so this should be resolved on their end the next time they deploy 👍

**Comment by WithoutPants** [comment]
This appears to be an issue with the TPDP interface not implementing an existing field in the stash-box schema. I don't think there's any actions to be done here.

**Comment by shanty-chits** [comment]
Does that mean TPDB can't be used at all? I'm still getting this error as of v0.24.1 - 2023-12-29:

```
scrapeSingleScene: input: scrapeSingleScene {"networkErrors":null,"graphqlErrors":[{"message":"Internal server error","path":["findScenesBySceneFingerprints",0,0,"performers",0,"performer","ethnicity"],"locations":[{"line":93,"column":2}]},{"message":"Internal server error","path":["findScenesBySceneFingerprints",0,0,"performers",0,"performer","hair_color"],"locations":[{"line":96,"column":2}]}]}
```

**Comment by Maista6969** [comment]
> Does that mean TPDB can't be used at all? I'm still getting this error as of v0.24.1 - 2023-12-29:
> 
> ```
> scrapeSingleScene: input: scrapeSingleScene {"networkErrors":null,"graphqlErrors":[{"message":"Internal server error","path":["findScenesBySceneFingerprints",0,0,"performers",0,"performer","ethnicity"],"locations":[{"line":93,"column":2}]},{"message":"Internal server error","path":["findScenesBySceneFingerprints",0,0,"performers",0,"performer","hair_color"],"locations":[{"line":96,"column":2}]}]}
> ```

This is a transient issue on TPDB's end, please see their Discord for details

**Comment by shanty-chits** [comment]
I inquired on their Discord, and they updated the server to fix the issue. Working great now.
