### ISSUE TITLE
[Bug Report] Previews for vertical videos are unnecessarily large

### ISSUE THREAD

**Issue by JadedMagician** [stashapp/stash#4830]
**Describe the bug**
When video previews for scenes are generated, Stash appears to shrink the input video's width down to 640px for the preview, without taking into account the aspect ratio. So a preview for a 16:9 video is 640x360, while a 4:3 video with the same vertical resolution as the 16:9 video will get a 640x480 preview, resulting in a higher vertical resolution. For vertical 9:16 videos, the preview is 640x1138, practically HD, and with a significantly higher file size on average than the 16:9 previews! Looking through my `stash/generated/screenshots` folder, most of the 16:9 previews are under 1MB, whereas most of the 9:16 previews are near or over 2MB, with some even going over 3MB. The same is true of the scrubber sprite images; sprites for 16:9 videos are 1440x810 and an average filesize of 500kb, while 9:16 video sprites are 1440x2556 with an average file size of 1.3MB.

If a user has scenes primarily from professional studios in their stash, this isn't much of an issue; but I have a large amount of content from OnlyFans and PornHub, where vertical videos are common, and these larger previews really balloon the size of my generated folder. Also, when actually viewing stash in a browser, with the scene cards zoomed to the largest level, the previews appear to cap out at 360px vertically, so the 640x1138 preview resolution is completely impractical.

As a solution, would it be possible to instead set the generator to give all previews a vertical resolution of 360px instead of a horizontal resolution of 640px, or perhaps make it so that stash checks the aspect ratio during generation so that it knows to give portrait videos reasonably sized previews and scrubber sprites?

**Screenshots**
Example screenshots from generated preview videos showing the disparity in size:
![mpv_240511_224913-1](https://github.com/stashapp/stash/assets/50552237/9d7ffd3f-4e63-43de-8985-a9c3c518fb84)
![mpv_240511_225020-1](https://github.com/stashapp/stash/assets/50552237/f9b4fe5d-1814-4ed1-9b52-719e6e1c86f8)

**Stash Version**
v0.25.1
Build hash:
bf7cb78d
Build time:
2024-03-13 03:30:08

**Desktop**
 - OS: Linux
 - Browser: Chrome

**Comment by feederbox826** [comment]
possibly related to https://github.com/stashapp/stash/issues/3426

but the root cause is because the height is set to be static, and the width as a ratio/factor. This helps account for 4:3 videos

**Comment by feederbox826** [comment]
Fixed by https://github.com/stashapp/stash/pull/6588

**Comment by JadedMagician** [comment]
> Fixed by [#6588](https://github.com/stashapp/stash/pull/6588)

This doesn't fix the issue at all. This only allows scrubber sprites to be resized. The previews that go in stash/generated/screenshots are still 640x1138 for 9:16 videos. The problem I described in the original post is not resolved, please reopen this. There needs to be a similar option under Preview Generation to set the resolution just as there is for the scrubber sprites.

(Sorry for replying so late, but I had stopped using Stash in the two years since I opened this issue, so I hadn't gotten around to testing this out until now.)
