### ISSUE TITLE
Tagger: search results displayed in incorrect order

### ISSUE THREAD

**Issue by smith113-p** [stashapp/stash#6109]
### Describe the bug

This is a bit odd but when I search by text in the tagger view (on tpdb) stash seems to reorder the results, and this means that the best result is not at the top

### Steps to reproduce

1. Go to tagger view 
2. Select theporndb 
3. Search by text for ` bip457 breastsinpain'`

### Expected behaviour

The result with studio code bip458 should be at the top as in https://theporndb.net/scenes?orderBy=most_relevant&page=1&q=bip454%20breastsinpain

### Screenshots or additional context

<img width="1008" height="2244" alt="Image" src="https://github.com/user-attachments/assets/02773f75-118d-4031-b27c-265c12be663f" />

### Stash version

v0.28.1-93-g14be3c24

### Relevant log output

```shell

```

**Comment by DogmaDragon** [comment]
Please censor or add SFW screenshot.

**Comment by smith113-p** [comment]
> Please censor or add SFW screenshot.

Sorry, done

**Comment by Maista6969** [comment]
Unable to reproduce this, I'm getting the exact results that you're expecting

<img width="1312" height="696" alt="Image" src="https://github.com/user-attachments/assets/dc8db946-ea6c-4ded-8f01-afa4eb77554e" />

<img width="1507" height="815" alt="Image" src="https://github.com/user-attachments/assets/8f27f0eb-d5a5-48e2-8c82-d63fda984903" />

**Comment by smith113-p** [comment]
Huh. That's also with the develop version?

**Comment by Maista6969** [comment]
Tested with both 28.1 and the latest develop version against the "untyped" `https://theporndb.net/graphql` endpoint

**Comment by feederbox826** [comment]
Also unable to replicate, getting same results as Maista, could it just be bad cache?

**Comment by smith113-p** [comment]
OK so I can still reproduce this.

I am using Chrome `142.0.7432.5 (Official Build) dev (64-bit) (cohort: Dev) `

What's interesting (maybe) is that in the network tab I can see that GraphQL returns the results in the correct order

So I guess this is either due to a plugin or due to my browser version?

**Comment by smith113-p** [comment]
Also happens with Firefox 143.0.1 (64-bit)

**Comment by smith113-p** [comment]
I don't know React but there seems to be some searching going on here: https://github.com/stashapp/stash/blob/15bf28d5be349407790be87d3b516f39525624eb/ui/v2.5/src/components/Tagger/scenes/StashSearchResult.tsx#L831

**Comment by smith113-p** [comment]
@Maista6969 @feederbox826 reading the code bit, I am wondering: did the local scene you used for your testing have any fingerprints?

I am also starting to wonder if that specific TPDB query has gotten less useful because it now has a fingerprint

Can you try `bip448 breastsinpain`? I won't submit fingerprints for that one. (Ideally your local scene would have a phash for this test)

**Comment by Maista6969** [comment]
That definitely explains it then, the [comment in the sorting function](https://github.com/stashapp/stash/blob/15bf28d5be349407790be87d3b516f39525624eb/ui/v2.5/src/components/Tagger/scenes/utils.ts#L85) explains that the results are sorted by similarity to your local scene, but the next few lines also show that scenes with zero fingerprints get sorted to the bottom of the search results

> Can you try `bip448 breastsinpain`? I won't submit fingerprints for that one.

Here's the result of this query on a fileless scene (the results are the same when the scene has fingerprints except Stash also displays a duration difference for the first two results)

<img width="1474" height="928" alt="Image" src="https://github.com/user-attachments/assets/2c2ae3d5-e5e3-4040-b475-773fb1869924" />

**Comment by smith113-p** [comment]
Yes, true, whether the local scene has a file/phash shouldn't matter.

OK, so I would argue that if none of the results are a good match, the ordering should stay the same because it is likely the best text match?

**Comment by DogmaDragon** [comment]
ThePornDB said it was fixed on their side.

**Comment by smith113-p** [comment]
Looks like tpdb now only returns a single scene for such queries, so that does fix the specific case I ran into 

Still not sure that his behavior is great in general, though
