### ISSUE TITLE
[Request] Add support to play files in external video player?

### ISSUE THREAD

**Issue by Cutters1982** [stashapp/stash#62]
Hi there

Really liking the app so far, but the internal video player and having to transcode multiple files is a real pain, and it will take up a lot of disk space.

Was wondering if you plan to allow support to play the video files externally via VLC/MPCHC which would eliminate the need in having to transcode the whole video? Or is that defeating the objective of what you want to do with this app?

I was hoping that maybe the app could act as a hub/media server, but the files play externally, but you would still have the little animated video previews etc)

Cheers

**Comment by rudi123github** [comment]
Similar to issue #52

**Comment by Leopere** [comment]
I think the idea is ultimately to attempt to leave the original file alone and do live transcode if needed to the browser.

If you consider this and the previous comment as a sufficient answer please close the ticket.

**Comment by rexii2300** [comment]
Yes I would love this feature. A large number of my files are mp4/flv encoded in mpeg4 instead of h264 and non of them are able to be played. All I see is black with the seekbar moving.

**Comment by Leopere** [comment]
Its a good feature if it gets submitted as a PR however it wouldn't make
sense for us to have a streaming app that doesn't stream.  We're just
currently waiting on @stash to get time to look into live transcoding which
seems to be the best solution.

**Comment by rexii2300** [comment]
Live transcoding would be fantastic!

How is everyone handling the problem right now? Is it best just to encode them all to h264 in mp4 container? sounds like a huge task with a big library?

**Comment by Leopere** [comment]
The other project that I would look at is https://github.com/JellyFin/JellyFin that is not really ideal for this kind of content but its a very mature streaming app.

**Comment by rexii2300** [comment]
jellyfin looks very polished for a steaming app. Most people seem to be recommending Plex or Emby.

The application of Stash can potentially be really wide. I was looking for a Lightroom equivalent for videos. Surprisingly nothing is out there. Most recommended Bridge but it is still clunky and metadata handling is horrible. Some more 'pro' level apps such as Kyno writes to a XML sidecar file and is pretty Spartan in terms of features. A non-adult version of Stash could be revolutionary for managing video content.

I'm a big fan of transcoding and streaming. Its magical when JW player works. Transcoding might be an issue for people that runs this in docker inside VMs. I see the two biggest strength of Stash as cataloging and streaming. Having the simple option and flexibility of play it via an external player will give people choices and only bring more people to Stash.
________________________________

**Comment by Leopere** [comment]
Don't go with Emby those recommendations are severely dated and after they closed Emby's source code I would no longer recommend it.  Especially since all of the commentary about terrible code discovered everywhere within the Emby base stack by the JellyFin FOSS fork team.  Plus JellyFin isn't fundamentally hostile towards FOSS contributions.  I can't speak to Plex but I just don't get a good vibe from it either.  JellyFin has the best feel in my opinion.

**Comment by ExceptionalError** [comment]
Wouldn't a link for an external player be an easy workaround until live transcoding is implemented?

**Comment by Leopere** [comment]
Theres no debate really against it I'm just mentioning that its in the
timeline to have transcoding and that it might just be equally as likely to
get either since I know the authors availability is low recently.

**Comment by rexii2300** [comment]
@Leopere do you have the ability to merge the PR into master?
Was looking at building my own docker container to test the PR and got completely overwhelmed . Might try a simple build to binary when I get a chance.

**Comment by Leopere** [comment]
I can merge things but typically I don't review go code the only thing I'm
really here for is the Docker stuff.

**Comment by Leopere** [comment]
Fixed along with #52 via #65

**Comment by nokatt** [comment]
> Fixed along with #52 via #65

I might oversee something but I haven't found a solution to that issue. The automatic transcoding leads to buffering and many videos still can't get played.
