### ISSUE TITLE
[Feature] Reassociate image with gallery

### ISSUE THREAD

**Issue by qqqzzzzzzqqq** [stashapp/stash#957]
On a scan for new images, they get added to a folder gallery automatically.

For whatever reason - maybe because I did my initial scan on unfinished code - many of my images have not been correctly added to galleries.

Subsequent scans ignore these images because they're already in the database and so this association never happens.

It would be great if there was a way to either manually rerun the association (like with the 'Generate' menu in the scene view) or if there was a way to auto-associate my whole DB of images with galleries, maybe as one of the optional checkboxes in the Generate task.

What do you think?

**Comment by WithoutPants** [comment]
I _think_ this is addressed already in the current dev/0.5 version. Can you please verify? If it doesn't, this should be considered a bug.

**Comment by qqqzzzzzzqqq** [comment]
Confirmed this is still an issue after updating to e4d91a0 and doing a (partial) scan.

It finds new images, and previously scanned images that are duplicated in multiple folders and adds them to (just one) gallery, but any previously scanned images that are unique - located in a single folder - are completely missed during the scan and not added to any galleries.

**Comment by WithoutPants** [comment]
I believe this is fixed with the file refactor changes. Let me know if it is not.
